(define (space eat-apple)
  (:literals (contains FOREST PLAYER)
             (contains FOREST ROCK)
             (contains FOREST TREE)
             (contains FOREST TWIG)
             (contains TREE APPLE)
             (portable APPLE)
             (portable ROCK)
             (portable TWIG)
             (waveable APPLE)
             (waveable ROCK)
             (waveable TWIG))
  (:steps (take PLAYER APPLE FOREST)
          (take PLAYER TWIG FOREST)
          (take PLAYER ROCK FOREST)
          (get-on ROCK PLAYER FOREST)
          (get-off ROCK PLAYER FOREST APPLE)
          (wave-spec APPLE PLAYER APPLE TREE FOREST ROCK)
          (wave-spec TWIG PLAYER APPLE TREE FOREST ROCK)
          (wave-spec ROCK PLAYER APPLE TREE FOREST ROCK)
          (eat APPLE PLAYER FOREST))
  (:axioms))