(define (problem take-stick)
    (:domain monkey-banana-2)
    (:init (contains LAB PLAYER)
           (contains LAB CHAIR)
           (contains LAB STICK)
           (contains LAB HOOK)
           (contains HOOK BANANA)
           (portable CHAIR)
           (portable STICK)
           (portable BANANA)
           (edible BANANA)
           (waveable CHAIR)
           (waveable STICK)
           (waveable BANANA))
    (:goal (contains PLAYER STICK))
)