(define (space take-stick)
  (:literals (contains HOOK BANANA)
             (contains LAB CHAIR)
             (contains LAB HOOK)
             (contains LAB PLAYER)
             (contains LAB STICK)
             (edible BANANA)
             (portable BANANA)
             (portable CHAIR)
             (portable STICK)
             (waveable BANANA)
             (waveable CHAIR)
             (waveable STICK))
  (:steps (take BANANA BANANA BANANA)
          (take BANANA BANANA STICK)
          (take BANANA BANANA CHAIR)
          (take BANANA BANANA HOOK)
          (take BANANA STICK BANANA)
          (take BANANA STICK STICK)
          (take BANANA STICK CHAIR)
          (take BANANA STICK HOOK)
          (take BANANA CHAIR BANANA)
          (take BANANA CHAIR STICK)
          (take BANANA CHAIR CHAIR)
          (take BANANA CHAIR HOOK)
          (take STICK BANANA BANANA)
          (take STICK BANANA STICK)
          (take STICK BANANA CHAIR)
          (take STICK BANANA HOOK)
          (take STICK STICK BANANA)
          (take STICK STICK STICK)
          (take STICK STICK CHAIR)
          (take STICK STICK LAB)
          (take STICK STICK HOOK)
          (take STICK STICK PLAYER)
          (take STICK CHAIR BANANA)
          (take STICK CHAIR STICK)
          (take STICK CHAIR CHAIR)
          (take STICK CHAIR LAB)
          (take STICK CHAIR HOOK)
          (take STICK CHAIR PLAYER)
          (take CHAIR BANANA BANANA)
          (take CHAIR BANANA STICK)
          (take CHAIR BANANA CHAIR)
          (take CHAIR BANANA HOOK)
          (take CHAIR STICK BANANA)
          (take CHAIR STICK STICK)
          (take CHAIR STICK CHAIR)
          (take CHAIR STICK LAB)
          (take CHAIR STICK HOOK)
          (take CHAIR STICK PLAYER)
          (take CHAIR CHAIR BANANA)
          (take CHAIR CHAIR STICK)
          (take CHAIR CHAIR CHAIR)
          (take CHAIR CHAIR LAB)
          (take CHAIR CHAIR HOOK)
          (take CHAIR CHAIR PLAYER)
          (take HOOK STICK LAB)
          (take HOOK CHAIR LAB)
          (take PLAYER STICK LAB)
          (take PLAYER CHAIR LAB))
  (:axioms))