(define (problem get-on-chair-and-wave-stick)
    (:domain monkey-banana-3)
    (:init (contains LAB PLAYER)
           (contains LAB CHAIR)
           (contains LAB STICK)
           (contains LAB HOOK)
           (contains HOOK BANANA)
           (portable CHAIR)
           (portable STICK)
           (portable BANANA)
           (waveable CHAIR)
           (waveable STICK)
           (waveable BANANA)
           (climbable CHAIR)
           (edible BANANA)
           (not (eaten PLAYER BANANA)))
    (:goal (eaten PLAYER BANANA))
)