(define (space escape-room-problem)
  (:literals (can-open CHEST)
             (can-open CUPBOARD)
             (can-see CHEST ROOM)
             (can-see CUPBOARD ROOM)
             (can-see DOOR ROOM)
             (can-see PLATFORM ROOM)
             (contains CHEST KEY)
             (contains CUPBOARD STOOL)
             (contains PLATFORM CHEST)
             (contains ROOM CUPBOARD)
             (contains ROOM DOOR)
             (contains ROOM PLATFORM)
             (contains ROOM PLAYER)
             (portable KEY)
             (portable STOOL))
  (:steps (take PLAYER STOOL ROOM)
          (open CUPBOARD STOOL ROOM PLAYER)
          (drop STOOL ROOM PLAYER)
          (get-on STOOL PLAYER ROOM))
  (:axioms))