(define (problem escape-room-problem)
    (:domain escape-room)
    (:init (contains ROOM CUPBOARD)
           (contains ROOM PLATFORM)
           (contains ROOM PLAYER)
           (contains ROOM DOOR)
           (contains CUPBOARD STOOL)
           (contains PLATFORM CHEST)
           (contains CHEST KEY)
           (can-open CUPBOARD)
           (can-open CHEST)
           (portable STOOL)
           (portable KEY)
           (can-see CUPBOARD ROOM)
           (can-see PLATFORM ROOM)
           (can-see CHEST ROOM)
           (can-see DOOR ROOM))
    (:goal (contains LAB STOOL))
)